imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

    ##Path to Node JS bin and lib
    node: /home/ec2-user/.nvm/versions/node/v6.11.5/bin/node
    node_paths: [/home/ec2-user/.nvm/versions/node/v6.11.5/lib/node_modules]
framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: []
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node:       "%node%"
            node_paths: "%node_paths%"
            apply_to:   "\.less$"
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js

        jquery_ui_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.js

        jquery_ui_css:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/jquery-ui.css

        jquery_ui_bg_diagonals_thick_90_eeeeee_40x40_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_diagonals-thick_90_eeeeee_40x40.png
            output: "images/ui-bg_diagonals-thick_90_eeeeee_40x40.png"

        jquery_ui_bg_glass_50_3baae3_1x400_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_glass_50_3baae3_1x400.png
            output: "images/ui-bg_glass_50_3baae3_1x400.png"

        jquery_ui_bg_glass_80_d7ebf9_1x400_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_glass_80_d7ebf9_1x400.png
            output: "images/ui-bg_glass_80_d7ebf9_1x400.png"

        jquery_ui_bg_glass_100_e4f1fb_1x400_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_glass_100_e4f1fb_1x400.png
            output: "images/ui-bg_glass_100_e4f1fb_1x400.png"

        jquery_ui_bg_highlight_hard_70_000000_1x100_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_highlight-hard_70_000000_1x100.png
            output: "images/ui-bg_highlight-hard_70_000000_1x100.png"

        jquery_ui_bg_highlight_hard_100_f2f5f7_1x100_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_highlight-hard_100_f2f5f7_1x100.png
            output: "images/ui-bg_highlight-hard_100_f2f5f7_1x100.png"

        jquery_ui_bg_highlight_soft_25_ffef8f_1x100_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_highlight-soft_25_ffef8f_1x100.png
            output: "images/ui-bg_highlight-soft_25_ffef8f_1x100.png"

        jquery_ui_bg_highlight_soft_100_deedf7_1x100_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-bg_highlight-soft_100_deedf7_1x100.png
            output: "images/ui-bg_highlight-soft_100_deedf7_1x100.png"

        jquery_ui_icons_2e83ff_256x240_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-icons_2e83ff_256x240.png
            output: "images/ui-icons_2e83ff_256x240.png"

        jquery_ui_icons_3d80b3_256x240_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-icons_3d80b3_256x240.png
            output: "images/ui-icons_3d80b3_256x240.png"

        jquery_ui_icons_72a7cf_256x240_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-icons_72a7cf_256x240.png
            output: "images/ui-icons_72a7cf_256x240.png"

        jquery_ui_icons_2694e8_256x240_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-icons_2694e8_256x240.png
            output: "images/ui-icons_2694e8_256x240.png"

        jquery_ui_icons_ffffff_256x240_png:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/cupertino/images/ui-icons_ffffff_256x240.png
            output: "images/ui-icons_ffffff_256x240.png"

        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]

        bootstrap_css_map:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css.map
            output: "css/bootstrap.css.map"
        bootstrap_css_theme_map:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css.map
            output: "css/bootstrap-theme.css.map"


        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
            output: "fonts/glyphicons-halflings-regular.woff2"
        site_css:
            inputs:
                - %kernel.root_dir%/Resources/public/css/site.less
            filters:
                - less
                - cssrewrite
        logging_css:
            inputs:
                - %kernel.root_dir%/Resources/public/css/logging.less
            filters:
                - less
                - cssrewrite
        logging_js:
            inputs:
                - %kernel.root_dir%/Resources/public/js/logging.js
        internal_css:
            inputs:
                - %kernel.root_dir%/Resources/public/css/internal.less
            filters:
                - less
                - cssrewrite

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
