# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    account.security_listener.class: AppBundle\Security\SecurityEventListner

services:
    webservice_user_provider:
        class: AppBundle\Security\User\WebserviceUserProvider
        arguments: [@database_connection,@logger]

    account.security_listener:
        class: %account.security_listener.class%
        arguments:
                - @security.token_storage
                - @router
                - @service_container
                - @request_stack

    ct_file_store.s3:
        class: AmazonS3
        arguments:
            options: { key: %aws_key%, secret: %aws_secret_key% }
