<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * BuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingRepository extends EntityRepository
{
    public function getBuildingsAssignedToUser($user_id)
    {
        $result = $this->getEntityManager()
                            ->createQueryBuilder()
                            ->select('b')
                            ->from('AppBundle:Building', 'b')
                            ->leftJoin('AppBundle:UserBuilding', 'u', \Doctrine\ORM\Query\Expr\Join::WITH, 'b.id = u.building')
                            ->where('u.user = :user_id')
                            ->setParameter(':user_id', $user_id)
                            ->orderBy('b.project')
                            ->getQuery()
                            ->getResult();

        return $result;
    }
}
