<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Repository\UserBuildingRepository;


/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function getAllUsersAssignedByBuilding($building_id)
    {
        $em = $this->getEntityManager();
        $sql = 'Select u.ID from users u join user_building ub on u.id = ub.user_id' .
                ' where ub.building_id = "' . $building_id . '"';
        $stmt = $em->getConnection()->prepare($sql);
        $result = $stmt->execute();

        return $stmt->fetchAll();
    }
}
